export const PROFILE = {
  name: 'Abdul Razzaque Ansari',
  first: 'ABDUL',
  last: 'RAZZAQUE',
  roles: ['B.Tech IT Student', 'Cybersecurity Explorer', 'Blockchain & Web3 Builder', 'AI × Web3 Hacker'],
  tagline: 'Aspiring IT Professional | B.Tech IT Student | Cybersecurity & Web3',
  bio: 'B.Tech IT student at Shree L. R. Tiwari College of Engineering (Diploma in IT, Vidyalankar Polytechnic 2023 — 2026). Focused on programming, cybersecurity, and Blockchain & Web3 — building secure, decentralized solutions.',
  email: 'a.razzaq8097@gmail.com',
  github: 'https://github.com/coderrazzaq',
  linkedin: 'https://www.linkedin.com/in/abdul-razzaque-ansari/',
  college: 'Shree L. R. Tiwari College of Engineering',
  status: 'Open to internships, projects & hackathons',
};

export const SKILLS = [
  { name: 'HTML', level: 95, cat: 'Frontend' },
  { name: 'CSS', level: 90, cat: 'Frontend' },
  { name: 'JavaScript', level: 85, cat: 'Languages' },
  { name: 'Responsive Design', level: 85, cat: 'Frontend' },
  { name: 'C', level: 80, cat: 'Languages' },
  { name: 'Python', level: 80, cat: 'Languages' },
  { name: 'C++', level: 75, cat: 'Languages' },
  { name: 'Java', level: 75, cat: 'Languages' },
  { name: 'Linux', level: 75, cat: 'Security' },
  { name: 'React', level: 70, cat: 'Frontend' },
  { name: 'Git', level: 70, cat: 'Tools' },
  { name: 'Cybersecurity', level: 70, cat: 'Security' },
  { name: 'Blockchain & Web3', level: 70, cat: 'Web3' },
  { name: 'Solidity', level: 65, cat: 'Web3' },
  { name: 'UI/UX Design', level: 65, cat: 'Frontend' },
  { name: 'Problem Solving', level: 90, cat: 'Tools' },
];

export const PROJECTS = [
  {
    id: 'tigergraph',
    title: 'TigerGraph Fraud Investigation Unit',
    desc: 'Docket-to-dossier workflow. Run investigations end-to-end: graph evidence, pattern reads, prior cases, then recommendations before and after new evidence — every step with its approval route.',
    tags: ['Next.js', 'TigerGraph', 'Fraud Detection', 'Graph DB', 'TypeScript', 'Tailwind'],
    cat: 'AI',
    grad: 'from-amber-400 via-orange-600 to-red-700',
    icon: '🕸️',
    year: '2025',
    accent: '#FBBF24',
  },
  {
    id: 'chainagent',
    title: 'Decentralised AI Agent Marketplace',
    desc: 'ChainAgent — built for ETHMumbai. Sellers proxy API keys, buyers & agents pay per query in USDC. x402 payment lifecycle, ENS subnames, instant Base Sepolia settlements. Anonymous, no KYC.',
    tags: ['Next.js', 'x402 Protocol', 'ENS', 'Base Sepolia', 'USDC', 'Web3'],
    cat: 'Web3',
    grad: 'from-violet-500 via-indigo-600 to-blue-700',
    icon: '🤖',
    year: '2025',
    accent: '#7C5CFF',
  },
  {
    id: 'trading',
    title: 'AI Trading Agent',
    desc: 'Intelligent blockchain companion that understands natural language, executes multi-chain trades and manages digital assets with enterprise-grade security. Just tell it in plain English.',
    tags: ['AI', 'Multi-Chain', 'DeFi', 'Natural Language', 'Security'],
    cat: 'AI',
    grad: 'from-emerald-400 via-teal-600 to-cyan-700',
    icon: '📈',
    year: '2025',
    accent: '#22E4EE',
  },
  {
    id: 'opbnb',
    title: 'opBNB AI Assistant',
    desc: 'Premium AI assistant on opBNB with ultra-low gas fees and 4000+ TPS. Secure auth, auto wallet generation, intelligent chain queries with glassmorphic UI.',
    tags: ['TypeScript', 'React', 'opBNB', 'Supabase', 'ethers.js', 'Framer Motion'],
    cat: 'Web3',
    grad: 'from-yellow-300 via-amber-500 to-orange-600',
    icon: '⚡',
    year: '2024',
    accent: '#FACC15',
  },
  {
    id: 'avax',
    title: 'Avalanche AI Blockchain Assistant',
    desc: 'Chat with AI to send AVAX, create tokens, mint NFTs and perform chain ops using natural language. Built for hackathons with IPFS + Web3 stack.',
    tags: ['TypeScript', 'React', 'Avalanche', 'AI', 'IPFS', 'Tailwind'],
    cat: 'Web3',
    grad: 'from-red-500 via-rose-600 to-pink-700',
    icon: '🏔️',
    year: '2024',
    accent: '#FB7185',
  },
  {
    id: 'urbania',
    title: 'Urbania Welfare Community Center',
    desc: 'Non-profit platform for community welfare programs, educational resources and support services — transforming lives, building stronger communities.',
    tags: ['HTML', 'CSS', 'JavaScript', 'Non-Profit', 'Responsive'],
    cat: 'Web',
    grad: 'from-sky-400 via-blue-600 to-indigo-800',
    icon: '🌍',
    year: '2024',
    accent: '#60A5FA',
  },
  {
    id: 'fitness',
    title: 'Make Your Body Shape — Fitness Club',
    desc: 'Dynamic fitness platform with workout programs, transformation tracking and motivational content to unleash potential and hit fitness goals.',
    tags: ['HTML', 'CSS', 'JavaScript', 'Fitness', 'Interactive'],
    cat: 'Web',
    grad: 'from-cyan-300 via-sky-500 to-indigo-700',
    icon: '💪',
    year: '2024',
    accent: '#C8FF2E',
  },
];

export const JOURNEY = [
  {
    title: 'B.Tech in Information Technology',
    org: 'Shree L. R. Tiwari College of Engineering',
    period: '2026 — Present',
    desc: 'Pursuing B.Tech in IT with focus on programming, software development and cybersecurity. Building secure, real-world projects at the intersection of AI × Blockchain.',
    icon: '🎓',
  },
  {
    title: 'Diploma in Information Technology',
    org: 'Vidyalankar Polytechnic',
    period: '2023 — 2026',
    desc: 'Strong foundations in programming fundamentals, web development, Linux and software engineering principles.',
    icon: '📜',
  },
  {
    title: 'Cybersecurity & Ethical Hacking',
    org: 'Self-Learning & Practice',
    period: '2024 — Present',
    desc: 'Vulnerability assessment, security analysis, Linux tooling, ethical hacking workflows and secure coding practices.',
    icon: '🛡️',
  },
  {
    title: 'Blockchain & Web3 Development',
    org: 'Hands-on Projects & Hackathons',
    period: '2024 — Present',
    desc: 'Solidity, Smart Contracts, DeFi, NFTs and dApps — building AI-powered Web3 projects and hackathon submissions.',
    icon: '⛓️',
  },
];
